# Site settings
title: Changelog da Rede Nossas Cidades
email: nicolas@nossascidades.org
description: >
  As últimas novidades sobre o desenvolvimento das plataformas da rede
  Nossas Cidades!
baseurl: ""
url: "http://changelog.nossascidades.org/"

# Build settings
markdown: kramdown
